server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/poscoict-glueframework/msa-service-config.git
          search-paths: '{application}'
management:
  endpoint: 
    env.enabled: true
  endpoints:
    web.exposure.include: *
encrypt:
  keyStore:
    location: /home/jinia/Desktop/jdk1.8.0_191/jre/lib/security/cacerts
    password: changeit
    alias: poscoict
    secret: yujin
